[build-system]
requires = ["setuptools>=64", "wheel", "ziglang"]
build-backend = "setuptools.build_meta"

[project]
name = "quickjs"
version = "1.19.4"
description = "Wrapping the quickjs C library."
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Petter Strandmark", email = "petter.strandmark@gmail.com"},
]

[tool.setuptools.packages.find]
include = ["quickjs*"]
